<!-- Generated by the Druxt devel template server middleware. -->
<template>
  <CTLayout class="container">
    <ClientOnly>
      <Teleport to=".header-slot">
        <CTParagraph>
          <slot name="field_recipe_category" />
          <slot name="field_tags" />
          <slot name="field_preparation_time" />
          <slot name="field_cooking_time" />
          <slot name="field_number_of_servings" />
          <slot name="field_difficulty" />

          <slot name="field_summary" />
        </CTParagraph>
      </Teleport>
    </ClientOnly>

    <template #sidebar>
      <CTParagraph class="ct-vertical-spacing--both">
        <slot name="field_ingredients" />
      </CTParagraph>
    </template>

    <CTParagraph class="ct-vertical-spacing--both">
      <slot name="field_recipe_instruction" />
    </CTParagraph>
  </CTLayout>
</template>

<script>
import Teleport from 'vue2-teleport'
import { DruxtEntityMixin } from 'druxt-entity'

export default {
  mixins: [DruxtEntityMixin],

  components: { Teleport },

  computed: {
    media: ({ entity }) => entity?.included?.find((o) => o?.id === entity?.relationships?.field_media_image?.data?.id),
    image: ({ entity, media }) => entity?.included?.find((o) => o?.id === media?.relationships?.field_media_image?.data?.id)
  },

  druxt: {
    query: {
      // fields: ["name","path","title"],
      include: ['field_media_image.field_media_image'],
    },
  },
}
</script>
